# Generated by Django 3.0.5 on 2020-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200523_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
