# Generated by Django 3.0.5 on 2020-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.IntegerField(default=None),
        ),
    ]
