# Generated by Django 3.0.5 on 2020-05-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_receptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('email', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('age', models.IntegerField(default=None)),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Receptionist')),
            ],
        ),
    ]
